---
name: Publish GHCR

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  MAIN_TAG: ghcr.io/${{ github.repository }}:latest
  MAIN_TAG_LOCAL: archivepodcast:latest
  DEB_VERSION: trixie
  DEB_TAG: ghcr.io/${{ github.repository }}:trixie
  AL_VERSION: al2023
  AL_TAG: ghcr.io/${{ github.repository }}:al2023
  AL_TAG_LOCAL: archivepodcast:al2023
  PYTEST_TAG_LOCAL: archivepodcast:pytest
  FFMPEG_TAG_LOCAL: archivepodcast:ffmpeg
jobs:
  publish-ghcr:
    name: "Publish GitHub Container Registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "has_version=true" >> $GITHUB_OUTPUT
          else
            echo "has_version=false" >> $GITHUB_OUTPUT
          fi

      # Region Login
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # region ffmpeg
      - name: Build ffmpeg container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/_dep_ffmpeg.Dockerfile
          push: false
          load: true
          tags: ${{ env.FFMPEG_TAG_LOCAL }}

      # region build
      - name: Build main docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.MAIN_TAG_LOCAL }}
          file: ./docker/main.Dockerfile

      - name: Build al docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.AL_TAG_LOCAL }}
          file: ./docker/main_al.Dockerfile

      # region run
      - name: Create instance directory
        run: |
          mkdir -p instance
          chmod 777 instance

      - name: Run main docker
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance --env AP_SELF_TEST=true ${{ env.MAIN_TAG_LOCAL }} archivepodcast

      - name: Run main docker waitress
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance ${{ env.MAIN_TAG_LOCAL }} waitress-serve --help

      - name: Run al docker
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance --env AP_SELF_TEST=true ${{ env.AL_TAG_LOCAL }} archivepodcast

      - name: Run al docker waitress
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance ${{ env.AL_TAG_LOCAL }} waitress-serve --help

      - name: Remove instance directory
        run: sudo rm -rf instance

      # region test
      - name: Build pytest docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/pytest.Dockerfile
          push: false
          load: true
          tags: ${{ env.PYTEST_TAG_LOCAL }}

      - name: Run pytest docker
        run: docker run --rm ${{ env.PYTEST_TAG_LOCAL }}

      # region publish
      - name: Build and push main Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/archivepodcast:latest
            ${{ env.DEB_TAG}}
            ${{ steps.version.outputs.has_version == 'true' && format('ghcr.io/{0}/archivepodcast:{1}-{2}', github.repository_owner, steps.version.outputs.version, env.DEB_VERSION) || '' }}
          file: ./docker/main.Dockerfile

      - name: Build and push al Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.AL_TAG }}
            ${{ steps.version.outputs.has_version == 'true' && format('ghcr.io/{0}/archivepodcast:{1}-{2}', github.repository_owner, steps.version.outputs.version, env.AL_VERSION) || '' }}
          file: ./docker/main_al.Dockerfile
