---
name: Publish GHCR

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  MAIN_TAG: kism/${{ github.repository_owner }}:latest
  MAIN_TAG_LOCAL: archivepodcast:latest
  PYTEST_TAG: archivepodcast:pytest
  FFMPEG_BOOKWORM_TAG: archivepodcast:ffmpeg-bookworm
jobs:
  publish-ghcr:
    name: "Publish GitHub Container Registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "has_version=true" >> $GITHUB_OUTPUT
          else
            echo "has_version=false" >> $GITHUB_OUTPUT
          fi

      # Region Login
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # region ffmpeg
      - name: Build ffmpeg main
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/_dep_ffmpeg_bookworm.Dockerfile
          push: false
          load: true
          tags: ${{ env.FFMPEG_BOOKWORM_TAG }}

      # region build
      - name: Build main docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.MAIN_TAG_LOCAL }}
          file: ./docker/main.Dockerfile

      # region run
      - name: Create instance directory
        run: mkdir -p instance

      - name: Run main docker
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance ${{ env.MAIN_TAG_LOCAL }} archivepodcast

      - name: Run main docker waitress
        run: docker run --rm --mount type=bind,source="$(pwd)"/instance,target=/app/instance ${{ env.MAIN_TAG_LOCAL }} waitress-serve --help

      - name: Remove instance directory
        run: sudo rm -rf instance

      # region test
      - name: Build pytest docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/pytest.Dockerfile
          push: false
          load: true
          tags: ${{ env.PYTEST_TAG }}

      - name: Run pytest docker
        run: docker run --rm ${{ env.PYTEST_TAG }}

      # region publish
      - name: Build and push main Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/archivepodcast:latest
            ${{ steps.version.outputs.has_version == 'true' && format('ghcr.io/{0}/archivepodcast:{1}', github.repository_owner, steps.version.outputs.version) || '' }}
          file: ./docker/main.Dockerfile
