---
name: Publish GHCR

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  MAIN_TAG: kism/${{ github.repository_owner }}:latest
  LAMBDA_TAG: kism/${{ github.repository_owner }}:lambda

jobs:
  publish-ghcr:
    name: "Publish GitHub Container Registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/archivepodcast:latest
          file: ./docker/main.Dockerfile

      - name: Build and push lambda Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/archivepodcast:lambda
          file: ./docker/lambda.Dockerfile
